### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by bkr32** [evilsocket/xray#27] opened 2017-07-14 16:17 UTC
after running 
make get_glide
make install_dependencies
i run into the following error on make build
```
gofmt -s -w .
vendor/golang.org/x/net/ipv4/batch.go:59:14: expected type, found '='
vendor/golang.org/x/net/ipv4/batch.go:78:2: expected declaration, found 'if'
vendor/golang.org/x/net/ipv6/batch.go:56:14: expected type, found '='
vendor/golang.org/x/net/ipv6/batch.go:69:2: expected declaration, found 'if'
Makefile:8: recipe for target 'format' failed
make: *** [format] Error 2
```

**Comment by evilsocket** [comment] 2017-07-14 16:18
Did you read the readme? What version of Go are you using?

**Comment by bkr32** [comment] 2017-07-14 19:15
yes i read the readme my go version is `go version go1.7.5 linux/amd64`

**Comment by wladiolo** [comment] 2017-07-14 20:30
Same error for me...
```
user@mypc:~/script/go-script/src/github.com/evilsocket/xray$ go version
go version go1.8.3 linux/amd64
user@mypc:~/script/go-script/src/github.com/evilsocket/xray$ go env | grep GOPATH
GOPATH="/home/user/script/go-script"
user@mypc:~/script/go-script/src/github.com/evilsocket/xray$ env | grep PATH
PATH=[...]:/usr/local/go/bin:/bin:/home/user/script/go-script/bin
user@mypc:~/script/go-script/src/github.com/evilsocket/xray$ uname -a
Linux mypc 4.4.0-83-generic #106~14.04.1-Ubuntu SMP Mon Jun 26 18:10:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I also tested the GO installation as suggested here https://golang.org/doc/install and it works.
```
user@mypc:~/script/go-script/src/hello$ ./hello 
hello, world
```
If you need some more info, let me know.
Thank you very much

**Comment by Minitram** [comment] 2017-07-14 20:42
I had the same error during build (tried go 1.8.3 and 1.7.6). After some time I figured that there is a syntax error in the source (and the parser message states _exactly_ what is wrong).
Just open the file $GOPATH/src/github.com/evilsocket/xray/vendor/golang.org/x/net/ipv4/batch.go, go to line 60 and remove the equal sign in statement `type Message = socket.Message` (i.e. it should be `type Message socket.Message`) than do the same in $GOPATH/src/github.com/evilsocket/xray/vendor/golang.org/x/net/ipv6/batch.go on line 56.
After correcting this everything went just fine.
Hope this helps.

**Comment by bkr32** [comment] 2017-07-15 07:03
thanks @Minitram that worked glad i didnt screw up following instructions

**Comment by evilsocket** [comment] 2017-07-15 09:19
i wonder why this didn't happen to other people as well 🤔

**Comment by fyoorer** [comment] 2017-07-16 04:24
I am getting this error while building docker image as well 🤔

**Comment by arbazkiraak** [comment] 2017-07-16 11:37
# make build
gofmt -s -w .
vendor/golang.org/x/net/ipv4/batch.go:59:14: expected type, found '='
vendor/golang.org/x/net/ipv4/batch.go:78:2: expected declaration, found 'if'
vendor/golang.org/x/net/ipv6/batch.go:56:14: expected type, found '='
vendor/golang.org/x/net/ipv6/batch.go:69:2: expected declaration, found 'if'
Makefile:8: recipe for target 'format' failed
make: *** [format] Error 2

Followed the instruction Given By @Minitram 

# make build
gofmt -s -w .
go-bindata -o cmd/xray/ui.go -pkg main ui
make: go-bindata: Command not found
Makefile:34: recipe for target 'static' failed
make: *** [static] Error 127

# go get -u github.com/jteeuwen/go-bindata/...

# make build
gofmt -s -w .
go-bindata -o cmd/xray/ui.go -pkg main ui
make: go-bindata: Command not found
Makefile:34: recipe for target 'static' failed
make: *** [static] Error 127

**Comment by arbazkiraak** [comment] 2017-07-16 11:56
Solved by : 
:+1: 
Manually : 

go get github.com/jteeuwen/go-bindata
cd $GOPATH/src/github.com/jteeuwen/go-bindata/go-bindata
go build

                                    (OR)
automatic  : 
:100: 
apt-get install go-bindata -y

**Comment by yojado** [comment] 2017-07-16 16:55
I got same error while try to build docker 

docker build -t xraydocker .
....
....
....
gofmt -s -w .
vendor/golang.org/x/net/ipv4/batch.go:59:14: expected type, found '='
vendor/golang.org/x/net/ipv4/batch.go:78:2: expected declaration, found 'if'
vendor/golang.org/x/net/ipv6/batch.go:56:14: expected type, found '='
vendor/golang.org/x/net/ipv6/batch.go:69:2: expected declaration, found 'if'
make: *** [Makefile:8: format] Error 2

so why this issue is marked as closed?

**Comment by bkr32** [comment] 2017-07-16 17:08
@yojado  the given solution by @Minitram worked

**Comment by CirKu17** [comment] 2017-07-17 23:27
Another different error even after the Minitram fix.
```
➜  xray git:(master) make build
gofmt -s -w .
go-bindata -o cmd/xray/ui.go -pkg main ui
# command-line-arguments
cmd/xray/bfs.go:57: undefined: AssetDir
cmd/xray/bfs.go:57: undefined: AssetInfo
Makefile:39: recipe for target 'build' failed
make: *** [build] Error 2
➜  xray git:(master) go get -u github.com/jteeuwen/go-bindata/...
➜  xray git:(master)  cd $GOPATH/src/github.com/jteeuwen/go-bindata/go-bindata
➜  go-bindata git:(master) ✗ go build
➜  go-bindata git:(master) ✗ cd ~/go/src/github.com/evilsocket/xray
➜  xray git:(master) make build
gofmt -s -w .
go-bindata -o cmd/xray/ui.go -pkg main ui
# command-line-arguments
cmd/xray/bfs.go:57: undefined: AssetDir
cmd/xray/bfs.go:57: undefined: AssetInfo
Makefile:39: recipe for target 'build' failed
make: *** [build] Error 2
➜  xray git:(master) go version
go version go1.8.3 linux/amd64

```
Probably related with this issue.

**Comment by phobosgroup** [comment] 2017-07-18 01:55
Also getting this error.

**Comment by mugundhan** [comment] 2017-07-18 03:28
the issue is with Golang 

https://github.com/golang/go/issues/20543

**Comment by madaratech** [comment] 2017-07-18 07:49
Hey @evilsocket, this error for installation introduced in this latest version of **XRAY**, it was not before, as @mugundhan told the fix for this new installation issue is removing **=**  sign in both respective file will solve the issue and worked for me as well.

```
vendor/golang.org/x/net/ipv4/batch.go:59
vendor/golang.org/x/net/ipv6/batch.go:56
```

Line to find in both file:
```
type Message = socket.Message
```
Replacing the = sign:
````
type Message socket.Message 
````
now **make build** should work!

**Closed** 2017-07-19 18:22 UTC
